#!/usr/bin/env python3
"""Generate the Kotlin lucide icon catalogue the UI draws from.

The original app pulls icons from `lucide-react`. There is no Kotlin port, so the
icons are fetched once from the lucide repository at a pinned tag and emitted as
the inner markup of a 24x24 stroke icon. Fetching beats hand-transcribing path
data: a mistyped coordinate produces a subtly wrong icon that no test would catch.

Only the icons the app actually uses are generated. To add one, put its lucide
file name in ICONS below and re-run.

Run:  python3 tools/generate_lucide.py
Out:  src/jsMain/kotlin/io/github/dayboard/ui/icons/LucideIcons.kt
"""

from __future__ import annotations

import os
import re
import sys
import urllib.request

# Pinned rather than `main`, so a re-run reproduces the same icons.
LUCIDE_VERSION = "1.34.0"
SOURCE = "https://raw.githubusercontent.com/lucide-icons/lucide/{v}/icons/{name}.svg"

# lucide file names, grouped by where the app uses them. Names follow lucide, not
# the original's React component names, which differ in places: `Loader2` in
# lucide-react is `loader-circle` here.
ICONS = [
    # `filter` was renamed `funnel` upstream. The Kotlin name keeps the original's
    # word so the tag-filter row in the spec is searchable in the code.
    ("funnel", "Filter"),
    # App shell and cards
    "timer", "maximize-2", "minimize-2", "chevron-down", "chevron-up",
    "chevron-right", "grip-vertical",
    # Pomodoro timer
    "rotate-ccw", "play", "pause", "skip-forward",
    # Clock and weather
    "loader-circle", "thermometer", "map-pin", "sun", "cloud-sun", "cloud",
    "cloud-drizzle", "cloud-rain", "cloud-snow", "cloud-lightning",
    # Tasks and notes
    "plus", "check", "pencil", "x", "tag", "trash-2",
    # Formatting toolbar
    "bold", "italic", "underline", "code",
    # Settings panel
    "settings", "monitor", "clock", "zap", "volume-2", "volume-x", "palette",
    "moon", "bell", "bell-off", "log-out",
    # Authentication
    "mail", "lock", "arrow-right",
]

OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "src", "jsMain", "kotlin", "io", "github", "dayboard", "ui", "icons",
    "LucideIcons.kt",
)


def pascal_case(name: str) -> str:
    """`cloud-sun` -> `CloudSun`, `maximize-2` -> `Maximize2`."""
    return "".join(part[:1].upper() + part[1:] for part in name.split("-"))


def fetch_body(name: str) -> str:
    """Return the inner markup of an icon, with the outer <svg> wrapper removed.

    The wrapper's attributes (viewBox, stroke, stroke-width, linecap, linejoin)
    are identical for every lucide icon, so they live once in the Kotlin renderer
    rather than 46 times in this file.
    """
    with urllib.request.urlopen(SOURCE.format(v=LUCIDE_VERSION, name=name)) as response:
        svg = response.read().decode("utf-8")

    inner = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.DOTALL)
    inner = re.sub(r"</svg>\s*$", "", inner, flags=re.DOTALL)
    # Collapse the pretty-printing: one line, no gaps between elements.
    inner = re.sub(r"\s+", " ", inner).strip()
    inner = re.sub(r">\s+<", "><", inner)

    if not inner:
        raise ValueError(f"{name}: no markup found")
    if '"""' in inner or "$" in inner:
        # Would break the Kotlin raw string this is emitted into.
        raise ValueError(f"{name}: markup contains a character the emitter cannot quote")
    return inner


def main() -> None:
    # An entry is either a lucide file name, or a (file name, Kotlin name) pair
    # for the icons lucide has since renamed.
    wanted = {
        (entry, pascal_case(entry)) if isinstance(entry, str) else entry
        for entry in ICONS
    }

    icons = []
    for file_name, kotlin_name in sorted(wanted, key=lambda pair: pair[1]):
        try:
            icons.append((kotlin_name, fetch_body(file_name)))
        except Exception as error:  # noqa: BLE001 - report and stop, do not emit a partial file
            sys.exit(f"failed on '{file_name}': {error}")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as out:
        out.write(
            f'''// Generated by tools/generate_lucide.py from lucide {LUCIDE_VERSION}. Do not edit.
package io.github.dayboard.ui.icons

/**
 * The lucide icons the app draws, as the inner markup of a 24x24 stroke icon.
 *
 * The shared wrapper attributes - the viewBox, `fill="none"`, `stroke="currentColor"`
 * and the 2px round-capped stroke - are applied once by the renderer in `Icon.kt`,
 * so `stroke="currentColor"` means every icon takes the colour of the text around it.
 *
 * Regenerate with `python3 tools/generate_lucide.py` rather than editing.
 */
enum class LucideIcon(internal val body: String) {{
'''
        )
        for kotlin_name, body in icons:
            out.write(f'    {kotlin_name}("""{body}"""),\n')
        out.write("}\n")

    print(f"  {OUT_PATH}")
    print(f"  {len(icons)} icons from lucide {LUCIDE_VERSION}")


if __name__ == "__main__":
    main()
